// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-8\"><div><h2 class=\"text-3xl font-bold text-gray-900 mb-2\">Welcome Back</h2><p class=\"text-gray-600\">Here's a summary of your internship search.</p></div><div hx-get=\"/dashboard/counts\" hx-trigger=\"load\" class=\"min-h-[120px]\"><div class=\"flex justify-center items-center h-full\"><div class=\"animate-pulse text-gray-400\">Loading stats...</div></div></div><div class=\"grid grid-cols-1 lg:grid-cols-3 gap-8\"><div hx-get=\"/dashboard/pipeline\" hx-trigger=\"load\" class=\"lg:col-span-2 min-h-[300px]\"><div class=\"bg-white p-6 rounded-xl border border-gray-200 shadow-sm animate-pulse\"><div class=\"h-6 w-48 bg-gray-200 rounded mb-6\"></div><div class=\"space-y-4\"><div class=\"h-4 w-full bg-gray-100 rounded\"></div><div class=\"h-4 w-full bg-gray-100 rounded\"></div><div class=\"h-4 w-full bg-gray-100 rounded\"></div></div></div></div><div class=\"space-y-6\"><div class=\"bg-indigo-900 p-6 rounded-xl text-white shadow-lg\"><h3 class=\"text-lg font-bold mb-2\">Quick Actions</h3><div class=\"space-y-3\"><a href=\"/positions\" class=\"block w-full text-center py-2 px-4 bg-white text-indigo-900 rounded-lg font-semibold hover:bg-indigo-50 transition-colors\">Add Position</a> <a href=\"/companies\" class=\"block w-full text-center py-2 px-4 border border-indigo-400 text-indigo-100 rounded-lg font-semibold hover:bg-indigo-800 transition-colors\">Manage Companies</a></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Dashboard").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
